version: 2.1

orbs:
  sonarscanner: psl/sonarscanner@0.0.4

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0-jdk
    steps:
      - checkout
      # Ajoutez ici les étapes pour la construction de votre projet

  sonarqube-connectivity-test:
    docker:
      - image: circleci/openjdk:11.0-jdk
    steps:
      - checkout
      - run:
          name: Test de connectivité à SonarQube
          command: |
            curl -v http://localhost:9000

  sonarqube-scan:
    docker:
      - image: circleci/openjdk:11.0-jdk
    steps:
      - checkout
      - run:
          name: Télécharger et installer SonarScanner
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner-cli-4.6.2.2472-linux.zip
      - run:
          name: Exécuter SonarScanner
          command: |
            ./sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner -X \
              # sonar-scanner.properties
              sonar.host.url=http://localhost:9000
              sonar.projectKey=demoProject
              sonar.projectName=demoProject
              sonar.projectVersion=1.0

workflows:
  version: 2
  main:
    jobs:
      - build
      - sonarqube-connectivity-test
      - sonarqube-scan
