version: 2.1

orbs:
  sonarscanner: psl/sonarscanner@0.0.4

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0-jdk
    steps:
      - checkout
      # Ajoutez ici les étapes pour la construction de votre projet

  sonarqube-scan:
    docker:
      - image: circleci/openjdk:11.0-jdk
    steps:
      - checkout
      - run:
          name: Télécharger et installer SonarQube scanner
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner-cli-4.6.2.2472-linux.zip
            export PATH="$PATH:$PWD/sonar-scanner-4.6.2.2472-linux/bin"
      - run:
          name: Exécuter SonarScanner
          command: |
            sonar-scanner \
              -Dsonar.projectKey=demoProject \
              -Dsonar.sources=. \
              -Dsonar.host.url=http://localhost:9000 \
              -Dsonar.login=sqb_c2ecb6ef393ec82578a31c3951ce0c2c2f10fd2d

workflows:
  version: 2
  main:
    jobs:
      - build
      - sonarqube-scan
