version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      # Install SonarQube Scanner
      - run:
          name: Download and install SonarQube Scanner
          command: |
            curl -sSL -o /tmp/sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            sudo unzip -d /opt /tmp/sonar-scanner-cli.zip
            sudo mv /opt/sonar-scanner-4.6.2.2472-linux /opt/sonar-scanner

      # Setup SonarQube properties
      - run:
          name: Setup SonarQube properties
          command: |
            sudo chown -R $USER:$USER /opt/sonar-scanner
            echo "sonar.host.url=http://localhost:9000" | sudo tee -a /opt/sonar-scanner/conf/sonar-scanner.properties
            echo "sonar.login=${SONAR_TOKEN}" | sudo tee -a /opt/sonar-scanner/conf/sonar-scanner.properties

      # Run SonarQube analysis with debug logging
      - run:
          name: Run SonarQube analysis
          command: |
            /opt/sonar-scanner/bin/sonar-scanner -X

workflows:
  version: 2
  build_and_analyze:
    jobs:
      - build
