version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0-jdk
    steps:
      - checkout
      
  deploy-test:
    docker:
      - image: circleci/openjdk:11.0-jdk
    steps:
      - checkout
      - run:
          name: Deploy to Test Environment
          command: |
            
            echo "Deploying to Test Environment..."

  deploy-staging:
    docker:
      - image: circleci/openjdk:11.0-jdk
    steps:
      - checkout
      - run:
          name: Deploy to Staging Environment
          command: |
            
            echo "Deploying to Staging Environment..."

  deploy-production:
    docker:
      - image: circleci/openjdk:11.0-jdk
    steps:
      - checkout
      - run:
          name: Deploy to Production Environment
          command: |
           
            echo "Deploying to Production Environment..."

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - deploy-test:
          requires:
            - build
      - deploy-staging:
          requires:
            - deploy-test
      - deploy-production:
          requires:
            - deploy-staging
