version: 2.1

jobs:
  sonarqube:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Install SonarQube Scanner
          command: |
            sudo apt-get update && sudo apt-get install -y unzip
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-linux.zip
            unzip sonar-scanner-cli-4.6.0.2311-linux.zip
            sudo mv sonar-scanner-4.6.0.2311-linux /opt/sonar-scanner
            sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner
            sonar-scanner -h -Dsonar.host.url=http://localhost:9000 -Dsonar.login=sqa_71bbb87c32ff59d42fdbc71a4793b30e76c79763

workflows:
  version: 2
  build_and_analyze:
    jobs:
      - sonarqube
