version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      # Exécution des tests avec Maven
      - run:
          name: Run Tests

workflows:
  build:
    jobs:
      - build
