version: 2.1

orbs:
  sonarscanner: psl/sonarscanner@0.0.4

jobs:
  # Sonarqube scanner   
  scan:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: /tmp/workspace
    environment:
      ENV_FILE: /tmp/workspace/.circleenv
      DOCKER_BUILDKIT: "1"
      BUILDKIT_PROGRESS: plain       
    steps:
      - checkout  
      - attach_workspace:
          at: /tmp/workspace   
      - run:
          name: Run Sonarscanner
          command: |
              export PATH="$PATH:$PWD/sonar-scanner-4.6.2.2472-linux/bin"
              sonar-scanner \
              -Dsonar.projectKey=$CIRCLE_BRANCH:$CIRCLE_PROJECT_REPONAME \
              -Dsonar.host.url=https://sonarqube.com/ \
              -Dsonar.login=$SONAR_TOKEN  

workflows: 
  version: 2
  main:
    jobs:
      - scan:
          context: sonarqube
