version: 2.1

orbs:
  sonarscanner: sonarsource/sonarcloud@1.0.1

jobs:
  # Sonarqube scanner   
  scan:
    docker:
      - image: circleci/openjdk:11.0-jdk
    working_directory: /tmp/workspace
    environment:
      ENV_FILE: /tmp/workspace/.circleenv
      DOCKER_BUILDKIT: "1"
      BUILDKIT_PROGRESS: plain       
    steps:
      - checkout  
      - attach_workspace:
          at: /tmp/workspace    
      - run:
          name: Install Sonarqube scanner 
          command: |
              sudo apt-get update
              sudo apt-get install -y openjdk-11-jdk
              wget -O sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
              unzip sonar-scanner.zip
              rm sonar-scanner.zip
      - run:
          name: Scan with SonarQube
          command: sonar-scanner \
            -Dsonar.projectKey=demoProject \
            -Dsonar.projectName='demoProject' \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=sqp_10f26cbe158cb8647b658f811072ff82fda5d9f4
