version: 2.1

orbs:
  sonarscanner: psl/sonarscanner@0.0.4

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0-jdk
    steps:
      - checkout
      # Ajoutez ici les étapes pour la construction de votre projet

  sonarqube-scan:
    docker:
      - image: circleci/openjdk:11.0-jdk
    steps:
      - checkout
      - run:
          name: Télécharger et installer SonarScanner
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner-cli-4.6.2.2472-linux.zip
